/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thundersoft_calculate_SimpleExpression */

#ifndef _Included_com_thundersoft_calculate_SimpleExpression
#define _Included_com_thundersoft_calculate_SimpleExpression
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thundersoft_calculate_SimpleExpression
 * Method:    sendExpressionStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_thundersoft_calculate_SimpleExpression_sendExpressionStr
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
