/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "calc.c"
//#include <android/log.h>
/* Header for class com.thundersoft.calculate_SimpleExpression */

#ifndef _Included_com_thundersoft_calculate_SimpleExpression
#define _Included_com_thundersoft_calculate_SimpleExpression
#ifdef __cplusplus

extern "C" {
#endif
JNIEXPORT jstring JNICALL Java_com_thundersoft_calculate_SimpleExpression_sendExpressionStr
  (JNIEnv* env, jobject thiz, jstring jstr) {
    jclass clazz = (*env)->GetObjectClass(env,thiz);
    if (clazz == NULL) return jstr;
    char *jchar2= (*env)->GetStringUTFChars(env,jstr,NULL);
	char *jret_str = parse_expression(jchar2);
	 //__android_log_print(ANDROID_LOG_DEBUG, "MY_JNI", "MY_JNIjret_str %s\n", jret_str);
    //jmethodID Method_onSimpleCompled = (*env)->GetMethodID(env,clazz,"onSimpleCompled","(Ljava/lang/String;)V");
    //if (Method_onSimpleCompled == NULL) return jstr;
    jstring jmsg = (*env)->NewStringUTF(env,jret_str);
    //(*env)->CallVoidMethod(env,thiz,Method_onSimpleCompled,jmsg);
    return jmsg;
}

#ifdef __cplusplus
}
#endif
#endif

